#!/bin/bash

# Lists the current directory's files in Vim, so you can edit it and save to rename them
# USAGE: vimv [file1 file2]
# https://github.com/thameera/vimv

if [ $# -ne 0 ]; then
    src=( "$@" )
else
    IFS=$'\r\n' GLOBIGNORE='*' command eval  'src=($(ls))'
fi

touch /tmp/vimv.$$
for ((i=0;i<${#src[@]};++i)); do
    echo "${src[i]}" >> /tmp/vimv.$$
done

vi /tmp/vimv.$$

IFS=$'\r\n' GLOBIGNORE='*' command eval  'dest=($(cat /tmp/vimv.$$))'

count=0
for ((i=0;i<${#src[@]};++i)); do
    if [ "${src[i]}" != "${dest[i]}" ]; then
        mv "${src[i]}" "${dest[i]}"
        ((count++))
    fi
done

echo "$count" files renamed.

rm /tmp/vimv.$$
